include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.gm.dart"
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
  
  errors:
    depend_on_referenced_packages: error

formatter:
  trailing_commas: preserve

linter:
  rules:
    always_specify_types: true
    always_declare_return_types: true
    annotate_overrides: true
    library_private_types_in_public_api: true
    use_super_parameters: true
    use_key_in_widget_constructors: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    camel_case_types: true
    constant_identifier_names: false
    no_leading_underscores_for_local_identifiers: true
    prefer_single_quotes: true
    prefer_relative_imports: true
    directives_ordering: true
    sort_child_properties_last: true
    prefer_constructors_over_static_methods: true
    unnecessary_lambdas: true
    unnecessary_this: true
    avoid_dynamic_calls: true
    avoid_empty_else: true
    avoid_init_to_null: true
    avoid_print: true
    avoid_redundant_argument_values: true
    avoid_returning_null_for_void: true
    avoid_unused_constructor_parameters: true
    cancel_subscriptions: true
    close_sinks: true
    exhaustive_cases: true
    unawaited_futures: true
    prefer_initializing_formals: false